### PR TITLE
Add execution of StatusChangedCmd

### PR DESCRIPTION
**Pull request by SergeoLacruz**
It seems that the execution of the StatusChangedCmd is missing. 
I also added a simple Makefile

### CODE REVIEW

**Comment by dehapama** [comment]
Thank you for committing to this project. I  have still one question regarding your patch. Don't we have to call waitpid on the status_changed_cmd_pid? To my understanding we get a zombie process if don't accept the exit status of status_changed_cmd_pid. There are already two waitpid-calls in the programm for  shutdown_cmd_pid and button_pressed_cmd_pid. We can either add a third block for the status_changed_cmd_pid or put the pid handling in an extra function. What do you think?

**Comment by SergeoLacruz** [comment]
You are right. I forgot about this. I just added another block. That's easier for the moment.

**Review by dehapama — APPROVED** [review]

**Review by dehapama — APPROVED** [review]

**Review by dehapama — COMMENTED** [review]
Why do you delete etc/init.d/piupsmonitor? It is for systems using sysv init instead of systemd. But I'm not sure, if there any distribution for raspberry pi using sysv init anymore.

**Review by dehapama — APPROVED** [review]
Binary file is deleted with your next commit. That is ok.

**Review by dehapama — APPROVED** [review]

**Pull request merged**
